### ISSUE TITLE
Create Modular Class for Handling Camera

### ISSUE THREAD

**Issue by Zoham** [Zoham/IntelliRISC#2]
### Tasks include:
- [ ] create a separate java class
- [ ] use the most efficient camera api provided by android
- [ ] implement methods and stop at the bare minimum skeleton of this utility class
- [ ] include camera permissions in the manifest file

### Note:
- use mnemonic names everywhere
- include javadoc/multiline comment (as and where applicable) for each new atomic feature/function/section

**Comment by sumit-03** [comment]
I am taking this issue.
